version: '3.8'

services:
  api:
    build:
      context: ./higia
      dockerfile: Dockerfile
    container_name: hackaton_api
    profiles: [api]
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hackaton_db
      - DB_USER=user
      - DB_PASSWORD=password
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=hegia
      - KEYCLOAK_CLIENT_ID=hackaton_client
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hackaton

  python_carga:
    build:
      context: ./python_carga
      dockerfile: Dockerfile
    container_name: python_carga
    profiles: [carga]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hackaton_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hackaton
  keycloak:
    container_name: hackaton_keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8443:8080
    volumes:
      - .docker/keycloak:/opt/keycloak/data/h2:rw
      - .docker/keycloak/import:/opt/keycloak/data/import:ro
    command:
      #      - start-dev # Utilizar esse comando quando a aplicacao estiver executando fora do Docker
      # Caso execute com o profile local, mude o hostname-url para http://localhost:8443
      # Caso execute com o profile docker, mude o hostname-url para http://keycloak:8080
      - start-dev --import-realm --hostname-url=http://localhost:8443 --hostname-admin-url=http://localhost:8443
    networks:
      - hackaton
  db:
    image: postgres:latest
    container_name: hackaton_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackaton_db
    volumes:
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/01-init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d hackaton_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackaton

networks:
  hackaton:
    driver: bridge